all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: root
    ansible_become: true
    security_mode: plaintext
preflight:
  hosts:
    192.168.0.240:
    192.168.0.241:
    192.168.0.242:
    192.168.0.243:
    192.168.0.244:
zookeeper:
  hosts:
    192.168.0.240:
broker:
  hosts:
    192.168.0.241:
      kafka:
        broker:
          id: 1
          ip: 192.168.0.241
    192.168.0.242:
      kafka:
        broker:
          id: 2
          ip: 192.168.0.242
    192.168.0.243:
      kafka:
        broker:
          id: 3
          ip: 192.168.0.243
schema-registry:
  hosts:
    192.168.0.244:
#connect-distributed:
#  hosts:
#    ip-172-31-20-223.us-east-2.compute.internal:
#kafka-rest:
#  hosts:
#    ip-172-31-20-223.us-east-2.compute.internal:
#ksql:
#  hosts:
#    ip-172-31-31-195.us-east-2.compute.internal:
#tools:
#  hosts:
#    ip-172-31-24-74.us-east-2.compute.internal:
#
