all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: root
    ansible_become: true
    security_mode: plaintext
preflight:
  hosts:
    192.168.65.201:
    192.168.65.202:
    192.168.65.203:
    192.168.65.204:
    192.168.65.205:
    192.168.65.206:
    192.168.65.211:
zookeeper:
  hosts:
    192.168.65.201:
    192.168.65.202:
    192.168.65.203:
broker:
  hosts:
    192.168.65.204:
      kafka:
        broker:
          id: 1
          ip: 192.168.65.204
    192.168.65.205:
      kafka:
        broker:
          id: 2
          ip: 192.168.65.205
    192.168.65.206:
      kafka:
        broker:
          id: 3
          ip: 192.168.65.206
schema-registry:
  hosts:
    192.168.65.211:
#connect-distributed:
#  hosts:
#    ip-172-31-20-223.us-east-2.compute.internal:
#kafka-rest:
#  hosts:
#    ip-172-31-20-223.us-east-2.compute.internal:
#ksql:
#  hosts:
#    ip-172-31-31-195.us-east-2.compute.internal:
#tools:
#  hosts:
#    ip-172-31-24-74.us-east-2.compute.internal:
#
